<a href="https://colab.research.google.com/github/Austinmukoro/Austinmukoro/blob/main/Self_practice_Mar_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
person =[
     {"name": "kemi","gender": "female","age": 21},
    {"name": "Yemi", "gender": "male","age":20},
     {"name": "Austin", "gender": "male", "age": 24}
 ]
#Checking for the data type
print(type(person))
# print(person[0]['name'])
# print('_'*15)
# #
# # # for loop
# for i in range(len(person)):
#     print(person[i]["name"])
# print('_'*15)
#
# #For getting the items of each attributes
# print(person[1].keys())
# print(person[1].values())
# print(person[1].get("name"))
# print('_'*15)
# #
# #for loop
# # for i in range(len(person)):
# #     print(person[i].keys())
# #     print(person[i].values())
# #     print(person[i].get("name"))
# # print('_'*15)
#
# #Solvig for a give range length
# for i in range(2):
#     print(person[i].keys())
#     print(person[i].values())
#     print(person[i].get("name"))
# print('_'*15)
#
# #Converting Dict to List
# #for loop
# for i in range(len(person)):
#     print(list(person[i].keys()))
#     print(list(person[i].values()))
#     print(person[i].get("name"))
# print('_'*15)
#for loop
# for i in range(len(person)):
#     print(person[i]["name"])
# print('_'*15)

# person =[{"name": "kemi","gender": "female","age": 21, "hobbies":["singing","Reading"]}]
# # ,{
# #     "name": "Yemi",
# #     "gender": "male",
# #     "age":20,
# # "hobbies:["singing","reading"]},
# # {"name": "Austin",
# # "gender": "male",
# #     "age": 24}
# # # ]
# print(person["hobbies"])
#
#
# # for i in range(len(person)):
# #     print(person[i]["names"])



#person =[{'id': 100, 'name' : 'ife', 'gender':'Female', 'age' :21, 'hobbies':['Reading', 'Traveling']},
#{'id': 101, 'name' : 'Lare', 'gender':'male', 'age' :23, 'hobbies':['Writing', 'Surfing the net']}
#]

# print(type(person))
# print(tuple(person))

print("--"*20)
for x,y in person[0].items():
    print(x,'-',y)

#Retrieve each hobbies of a student with their names

for i in range(len(person)):
      print(person[i].get('name'),
      person[i].get('hobbies'))
      print("--"*20)

      #Retrieve records of student whose age is greater than 21
# for persons in person:
#     if persons['age']> 21:
#         print(person[i].get('name'),
#         person[i].get('age'),
#         person[i].get('hobbies'),
#         person[i].get('gender'))
# print("--"*20)

#If the value of a name is'Lare',
#display his hobbies

# for persons in person:
#     if persons.get('name')=='Lare':
#         print(persons.get('hobbies'))
# print("--"*20)
#
# #6.Do have a wonderful weekend coding
for i in range(len(person)):
    print(person[i].get('name'), person)
print("--"*20)
#
# engsp = dict()
# engsp ['one'] = 'un'
# engsp ['two'] = 'deux'
# engsp ['three'] = 'Trois'
# print(engsp.keys())
# print(engsp.values())
# print(engsp.items())
#
# print("--"*20)

# result = 0
# for i in range (1,11):
#     result+ =i
#     result = result +i
#     print(result)




print("--"*20)


#converting 1234 to word
phone = input("phone ")
digts_mapping =[
{
"1":"One",
"2":"Two",
"3":"Three",
"4": "Four"
}
]
output = " "
for ch in phone:
    output+=digts_mapping.get(ch,"!")+""
print(output)

In [ ]:
#ASSIGNMENT ___ TUPLES

person = ("John", "25","gender")
print(person)

('John', '25', 'gender')


In [ ]:
person [1] =20
print(person)

In [ ]:
#LIST
grocery_list = ["milk","bread","eggs","bananas"]

print(grocery_list[0])

grocery_list.append("chocolate")

print(grocery_list)

grocery_list.remove("milk")

 print(grocery_list)


In [ ]:
# SETS
unique_numbers = {1,2,3,4,5}

#Add number 6 to the unique_number
unique_numbers.add(6)
print(unique_numbers)

#print the length of the unique_numbers
print (len(unique_numbers))


In [ ]:
# Try to add a duplicate number and see what happens
unique_numbers.add(4)
print(unique_numbers)

In [ ]:
#####################     DICTIONARY



In [ ]:
employees = {"name": "John", "age": 25, "position": "Developer", "salary": 3000}

# Print the type of the employees dictionary
print(type(employees))

# Access the value associated with the "name" key
print(employees['name'])

# Change the employee's position to "Manager"
employees["position"] = "Manager"

# Print the modified employees dictionary
print(employees)

In [ ]:
# DATA WRANGLING

In [ ]:
import pandas as pd

In [ ]:
url_link ='https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue'

In [ ]:
company_data = pd.read_html(url_link)

In [ ]:
type(company_data)

list

In [ ]:
company_data[0].head()

Rank                             Name     Industry      Revenue  \
  Rank                             Name     Industry USD millions   
0    1                          Walmart       Retail     $611,289   
1    2                     Saudi Aramco  Oil and gas     $603,651   
2    3                           Amazon       Retail     $574,785   
3    4  State Grid Corporation of China  Electricity     $530,009   
4    5                            Vitol  Commodities     $505,000   

        Profit Employees Headquarters[note 1] State-owned               Ref.  \
  USD millions Employees Headquarters[note 1] State-owned Unnamed: 8_level_1   
0      $11,680   2100000        United States         NaN                [1]   
1     $159,069     70496         Saudi Arabia         NaN                [4]   
2      $30,425   1525000        United States         NaN                [5]   
3       $8,192    870287                China         NaN                [6]   
4      $15,000      1560          Switzerland         NaN             [7][8]   

  Unnamed: 9_level_0  
  Revenue per worker  
0        $291,090.00  
1      $8,562,911.37  
2           $376,908  
3        $609,004.85  
4    $323,717,948.72

In [ ]:
company_data = company_data[0]

In [ ]:
type(company_data)

pandas.core.frame.DataFrame

In [ ]:
company_data.columns

MultiIndex([(                'Rank',                 'Rank'),
            (                'Name',                 'Name'),
            (            'Industry',             'Industry'),
            (             'Revenue',         'USD millions'),
            (              'Profit',         'USD millions'),
            (           'Employees',            'Employees'),
            ('Headquarters[note 1]', 'Headquarters[note 1]'),
            (         'State-owned',          'State-owned'),
            (                'Ref.',   'Unnamed: 8_level_1'),
            (  'Unnamed: 9_level_0',   'Revenue per worker')],
           )

In [ ]:
# RENAMING COLUMN NAMES

In [ ]:
company_data.columns = company_data.columns.get_level_values(0)

In [ ]:
company_data.columns

Index(['Rank', 'Name', 'Industry', 'Revenue', 'Profit', 'Employees',
       'Headquarters[note 1]', 'State-owned', 'Ref.', 'Unnamed: 9_level_0'],
      dtype='object')

In [ ]:
company_data.head()

Rank                             Name     Industry   Revenue    Profit  \
0     1                          Walmart       Retail  $611,289   $11,680   
1     2                     Saudi Aramco  Oil and gas  $603,651  $159,069   
2     3                           Amazon       Retail  $574,785   $30,425   
3     4  State Grid Corporation of China  Electricity  $530,009    $8,192   
4     5                            Vitol  Commodities  $505,000   $15,000   

   Employees Headquarters[note 1]  State-owned    Ref. Unnamed: 9_level_0  
0    2100000        United States          NaN     [1]        $291,090.00  
1      70496         Saudi Arabia          NaN     [4]      $8,562,911.37  
2    1525000        United States          NaN     [5]           $376,908  
3     870287                China          NaN     [6]        $609,004.85  
4       1560          Switzerland          NaN  [7][8]    $323,717,948.72

In [ ]:
company_data = company_data.rename(columns={'Rank': 'Ranking', 'Name': 'Company Name', 'Headquarters[note 1]':'Headquarters'})

In [ ]:
company_data.head()

Ranking                     Company Name     Industry   Revenue    Profit  \
0        1                          Walmart       Retail  $611,289   $11,680   
1        2                     Saudi Aramco  Oil and gas  $603,651  $159,069   
2        3                           Amazon       Retail  $574,785   $30,425   
3        4  State Grid Corporation of China  Electricity  $530,009    $8,192   
4        5                            Vitol  Commodities  $505,000   $15,000   

   Employees   Headquarters  State-owned    Ref. Unnamed: 9_level_0  
0    2100000  United States          NaN     [1]        $291,090.00  
1      70496   Saudi Arabia          NaN     [4]      $8,562,911.37  
2    1525000  United States          NaN     [5]           $376,908  
3     870287          China          NaN     [6]        $609,004.85  
4       1560    Switzerland          NaN  [7][8]    $323,717,948.72

In [ ]:
# Remove $ sign and replace with nothing from the Revenue and Profit column

In [ ]:
company_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Ranking             50 non-null     int64  
 1   Company Name        50 non-null     object 
 2   Industry            50 non-null     object 
 3   Revenue             50 non-null     object 
 4   Profit              50 non-null     object 
 5   Employees           50 non-null     int64  
 6   Headquarters        50 non-null     object 
 7   State-owned         0 non-null      float64
 8   Ref.                50 non-null     object 
 9   Unnamed: 9_level_0  50 non-null     object 
dtypes: float64(1), int64(2), object(7)
memory usage: 4.0+ KB


In [ ]:
company_data['Revenue'].head()

KeyError: 'Revenue'

In [ ]:
company_data['Revenue'] = company_data['Revenue'].str.replace('$','')

<ipython-input-220-06a20b630ad6>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  company_data['Revenue'] = company_data['Revenue'].str.replace('$','')


In [ ]:
company_data.head()

Ranking                     Company Name     Industry  Revenue   Profit  \
0        1                          Walmart       Retail  611,289   11,680   
1        2                     Saudi Aramco  Oil and gas  603,651  159,069   
2        3                           Amazon       Retail  574,785   30,425   
3        4  State Grid Corporation of China  Electricity  530,009    8,192   
4        5                            Vitol  Commodities  505,000   15,000   

   Employees   Headquarters  State-owned    Ref. Unnamed: 9_level_0  
0    2100000  United States          NaN     [1]        $291,090.00  
1      70496   Saudi Arabia          NaN     [4]      $8,562,911.37  
2    1525000  United States          NaN     [5]           $376,908  
3     870287          China          NaN     [6]        $609,004.85  
4       1560    Switzerland          NaN  [7][8]    $323,717,948.72

In [ ]:
company_data['Profit'] = company_data['Profit'].str.replace('$','')

<ipython-input-222-ecbe9e132cce>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  company_data['Profit'] = company_data['Profit'].str.replace('$','')


In [ ]:
company_data.head()

Ranking                     Company Name     Industry  Revenue   Profit  \
0        1                          Walmart       Retail  611,289   11,680   
1        2                     Saudi Aramco  Oil and gas  603,651  159,069   
2        3                           Amazon       Retail  574,785   30,425   
3        4  State Grid Corporation of China  Electricity  530,009    8,192   
4        5                            Vitol  Commodities  505,000   15,000   

   Employees   Headquarters  State-owned    Ref. Unnamed: 9_level_0  
0    2100000  United States          NaN     [1]        $291,090.00  
1      70496   Saudi Arabia          NaN     [4]      $8,562,911.37  
2    1525000  United States          NaN     [5]           $376,908  
3     870287          China          NaN     [6]        $609,004.85  
4       1560    Switzerland          NaN  [7][8]    $323,717,948.72

In [ ]:
 # RENAME COLUMN NAME

In [ ]:
company_data.rename(columns={'Revenue':'Revenue($)','Profit':'Profit($)'},inplace=True)

In [ ]:
company_data.head()

Ranking                     Company Name     Industry Revenue($) Profit($)  \
0        1                          Walmart       Retail    611,289    11,680   
1        2                     Saudi Aramco  Oil and gas    603,651   159,069   
2        3                           Amazon       Retail    574,785    30,425   
3        4  State Grid Corporation of China  Electricity    530,009     8,192   
4        5                            Vitol  Commodities    505,000    15,000   

   Employees   Headquarters  State-owned    Ref. Unnamed: 9_level_0  
0    2100000  United States          NaN     [1]        $291,090.00  
1      70496   Saudi Arabia          NaN     [4]      $8,562,911.37  
2    1525000  United States          NaN     [5]           $376,908  
3     870287          China          NaN     [6]        $609,004.85  
4       1560    Switzerland          NaN  [7][8]    $323,717,948.72

In [ ]:
# check for Irregularities

In [ ]:
#company_data ['Revenue $'].unique()

In [ ]:
company_data['Revenue($)'].unique()

array(['611,289', '603,651', '574,785', '530,009', '505,000', '483,019',
       '471,154', '413,680', '394,328', '386,201', '324,162', '322,467',
       '318,476', '305,885', '302,089', '293,685', '288,309', '282,836',
       '276,711', '274,491', '263,310', '255,984', '248,891', '246,252',
       '238,587', '234,129', '226,954', '222,535', '214,766', '211,915',
       '202,753', '188,888', '187,061', '181,566', '181,364', '180,516',
       '180,012', '175,702', '173,834', '171,669', '171,189', '167,832',
       '165,000', '164,762', '163,037', '161,698', '159,800', '159,371',
       '158,057', '157,403'], dtype=object)

In [ ]:
# Replacing commas with nothing

In [ ]:
company_data ['Revenue($)']=company_data['Revenue($)'].str.replace(',','')

In [ ]:
company_data.head()

Ranking                     Company Name     Industry  Revenue($)  \
0        1                          Walmart       Retail    611289.0   
1        2                     Saudi Aramco  Oil and gas    603651.0   
2        3                           Amazon       Retail    574785.0   
3        4  State Grid Corporation of China  Electricity    530009.0   
4        5                            Vitol  Commodities    505000.0   

   Profit($)  Employees   Headquarters  State-owned    Ref. Unnamed: 9_level_0  
0        NaN    2100000  United States          NaN     [1]        $291,090.00  
1        NaN      70496   Saudi Arabia          NaN     [4]      $8,562,911.37  
2        NaN    1525000  United States          NaN     [5]           $376,908  
3        NaN     870287          China          NaN     [6]        $609,004.85  
4        NaN       1560    Switzerland          NaN  [7][8]    $323,717,948.72

In [ ]:
# Converting Object (Revenue and Profit) to float

In [ ]:
company_data['Revenue($)'] = company_data['Revenue($)'].astype(float)

In [ ]:
company_data.head()

Ranking                     Company Name     Industry  Revenue($)  \
0        1                          Walmart       Retail    611289.0   
1        2                     Saudi Aramco  Oil and gas    603651.0   
2        3                           Amazon       Retail    574785.0   
3        4  State Grid Corporation of China  Electricity    530009.0   
4        5                            Vitol  Commodities    505000.0   

  Profit($)  Employees   Headquarters  State-owned    Ref. Unnamed: 9_level_0  
0    11,680    2100000  United States          NaN     [1]        $291,090.00  
1   159,069      70496   Saudi Arabia          NaN     [4]      $8,562,911.37  
2    30,425    1525000  United States          NaN     [5]           $376,908  
3     8,192     870287          China          NaN     [6]        $609,004.85  
4    15,000       1560    Switzerland          NaN  [7][8]    $323,717,948.72

In [ ]:
company_data ['Profit($)'].unique()

array(['11,680', '159,069', '30,425', '8,192', '15,000', '21,080',
       '9,657', '55,740', '99,803', '20,120', '4,149', '6,994', '4,234',
       '−22,819', '15,233', '−19,961', '59,972', '3,560', '18,110',
       '20,526', '17,320', '−2,487', '35,465', '1,699', '42,398', '5,844',
       '4,751', '53,589', '73,307', '48,145', '17,669', '38,524',
       '12,454', '−933', '6,668', '14,516', '11,024', '–1', '2,035',
       '11,528', '17,641', '...', '16,988', '1,800', '2,493', '8,723',
       '−1,981', '15,252'], dtype=object)

In [ ]:
# Replacing commas with nothing

In [ ]:
company_data['Profit($)'] = pd.to_numeric(company_data['Profit($)'], errors='coerce').astype(float)

In [ ]:
company_data['Profit($)'] = company_data['Profit($)'].astype(float)

In [ ]:
company_data.head()

Ranking                     Company Name     Industry  Revenue($)  \
0        1                          Walmart       Retail    611289.0   
1        2                     Saudi Aramco  Oil and gas    603651.0   
2        3                           Amazon       Retail    574785.0   
3        4  State Grid Corporation of China  Electricity    530009.0   
4        5                            Vitol  Commodities    505000.0   

   Profit($)  Employees   Headquarters  State-owned    Ref. Unnamed: 9_level_0  
0    11680.0    2100000  United States          NaN     [1]        $291,090.00  
1   159069.0      70496   Saudi Arabia          NaN     [4]      $8,562,911.37  
2    30425.0    1525000  United States          NaN     [5]           $376,908  
3     8192.0     870287          China          NaN     [6]        $609,004.85  
4    15000.0       1560    Switzerland          NaN  [7][8]    $323,717,948.72

In [ ]:
import json

In [ ]:
import numpy as np
array_1D = np.array([10,11,12,13, 14])
array_1D
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D


array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [ ]:
first_column = [row[0] for row in my_array]

In [ ]:
# Slice the first column of the 2-D array

In [ ]:
array_2D = np.array([[20, 30, 40, 50, 60],
                     [43, 54, 65, 76, 87],
                     [11, 22, 33, 44, 55]])

In [ ]:
array_2D[0:3,0:1]

array([[20],
       [43],
       [11]])

In [ ]:
first_column = array_2D[:, 0]

print("Original 2-D Array:")

In [ ]:
print("Original 2-D Array:")

In [ ]:
#Slice the last two columns of the 2-nd row of the 2-D array


In [ ]:
array_slice=array_2D[1:2,3:5]

In [ ]:
array_slice

array([[76, 87]])

In [ ]:
# Slice the 2-nd row of the 2-D array excluding the last two columns

In [ ]:
array_3D = np.array([[20, 30, 40, 50, 60],
                     [43, 54, 65, 76, 87],
                     [11, 22, 33, 44, 55]])

In [ ]:
array_slice= array_3D[0]

In [ ]:
array_slice

array([[ 1,  2,  3,  4,  5],
       [11, 21, 31, 41, 51]])

In [ ]:
array_slice= array_3D[0:2,0:2,3:5]

In [ ]:
array_slice

array([[[ 4,  5],
        [41, 51]],

       [[14, 15],
        [54,  5]]])

In [ ]:
array_slice= array_3D[0:2,0:2,1:4]

In [ ]:
array_slice

array([[[ 2,  3,  4],
        [21, 31, 41]],

       [[12, 13, 14],
        [52, 53, 54]]])

In [ ]:
step_3D

In [ ]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [ ]:
step_3D = array_3D[0:2:2, 0:2:2, 0:5:2]

In [ ]:
step_3D

array([[[1, 3, 5]]])